spring:
  application:
    name: harvest-synchronization
server:
  shutdown: graceful
  port: 8011
logging:
  level:
    root: INFO
    web: DEBUG
  file:
    path: /
    name: harvest-synchronization.log
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /system
jira:
  domain: https://usko-incorporated.atlassian.net
  username: abialiauski@uskoinc.com
#  token: zTErdw09R9vMvqS0JrE7D44A
  token: My4hWPICrAZUheI0OulXA39B